import fs from 'fs'
import path from 'path'
import { formatSparkleBuildStamp } from './writeBuildStampCore'

const root = process.cwd()
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')) as {
  version: string
}
const stamp = formatSparkleBuildStamp(new Date())
const outPath = path.join(root, 'src/shared/buildStamp.ts')
const content = `// Auto-generated by scripts/write-build-stamp.ts — do not edit manually.
export const SPARKLE_BUILD_STAMP = '${stamp}'
export const SPARKLE_SEMVER = '${pkg.version}'
`
fs.writeFileSync(outPath, content, 'utf8')
console.log(`[write-build-stamp] ${stamp} (semver ${pkg.version}) → ${outPath}`)
